spring:
  session:
    store-type: jdbc
  profiles:
    include: oauth
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engin: innodb
    show-sql: true

  h2:
    console:
      enabled: true

